server:
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: NexusGrade

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 25

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources/static,src/main/resources/templates